
POST http://localhost:8080/badge/create HTTP/1.1
Content-Type: application/json

{
    "badgeName":"Test Badge 1234",
    "isApproved": false,
    "description":"test badge "
}


###
GET http://localhost:8080/user/list HTTP/1.1
Content-Type: application/json
###
DELETE  http://localhost:8080/badge/delete HTTP/1.1
Content-Type: application/json
###
GET http://localhost:8080/badge/list HTTP/1.1
Content-Type: application/json

###

# GET  http://localhost:8080/badge HTTP/1.1

###

GET http://localhost:3000/userdocuments
Content-Type: application/json
###
POST http://localhost:8080/badge/badges HTTP/1.1
Content-Type: application/json

{
"ids":["623a1c4c3c3c23b9517a2e34","623a1b473c3c23b9517a0ec5"]
}
